builds:
  - genome/global
  - genome/north-america
additional_inputs:
  - name: ppx_restricted
    metadata: "s3://nextstrain-data/files/workflows/measles/metadata_restricted.tsv.zst"
    sequences: "s3://nextstrain-data/files/workflows/measles/sequences_restricted.fasta.zst"
  - name: private
    metadata: ../placement/private_metadata.tsv
    sequences: ../placement/private_sequences.fasta
files:
    auspice_config: 'build-configs/state_focused/{build}.json'
custom_subsample:
    genome/global:
        defaults:
            exclude_ambiguous_dates_by: year
        samples:
            state:
                query: division == "Washington"
                max_sequences: 3000
                min_length: 13000
                min_date: "1950"
                exclude:
                    - defaults/dropped_strains.txt
            continental:
                query: division != "Washington" & region == "North America"
                max_sequences: 1500
                min_length: 13000
                min_date: "1950"
                exclude:
                    - defaults/dropped_strains.txt
            global:
                query: region != "North America"
                max_sequences: 3000
                min_length: 13000
                min_date: "1950"
                include:
                    - defaults/include_strains_genome.txt
                exclude:
                    - defaults/dropped_strains.txt
            nearest-strains:
                method: hamming
                focal_sample: global
                context_sample: continental
                k: 20
                ignore_missing_data: all

    genome/north-america:
        defaults:
            exclude_ambiguous_dates_by: year
        samples:
            state:
                query: division == "Washington"
                max_sequences: 3000
                min_length: 13000
                min_date: "1950"
                exclude:
                    - defaults/dropped_strains.txt
            continental:
                query: division != "Washington" & region == "North America"
                max_sequences: 3000
                min_length: 13000
                min_date: "1950"
                exclude:
                    - defaults/dropped_strains.txt
            global:
                query: region != "North America"
                max_sequences: 1500
                min_length: 13000
                min_date: "1950"
                include:
                    - defaults/include_strains_genome.txt
                exclude:
                    - defaults/dropped_strains.txt
            nearest-strains:
                method: hamming
                focal_sample: global
                context_sample: continental
                k: 20
                ignore_missing_data: all
refine:
    genome/global: >-
        --timetree
        --coalescent opt
        --date-inference marginal
        --date-confidence
        --clock-filter-iqd 8
        --stochastic-resolve
        --divergence-units mutations
    genome/north-america: >-
        --timetree
        --coalescent opt
        --date-inference marginal
        --date-confidence
        --clock-filter-iqd 8
        --stochastic-resolve
        --divergence-units mutations

export:
    genome/global: &general_export
        metadata_columns:
            - strain
            - division
            - location
            - dataUseTerms
            - restrictedUntil
            - PPX_accession
            - INSDC_accession
            - county
        color_by_metadata:
            - genotype
            - date
            - county
            - division
            - region
            - country
            - genotype_ppx
            - dataUseTerms
    genome/north-america:
      <<: *general_export
